### ISSUE TITLE
Typo 3.1 Prepwork

### ISSUE THREAD

**Issue by lauramjohnson** [LaunchCodeEducation/skills-back-end-java#1]
Do only Lesson 5, "Introduction" through "Hello World in IntelliJ". These lessons provide a great introduction to how Java programs run, and how to set up the tools you need to work with Java **applictions**. This **poriton** of Lesson **4** is **indepdendent** from Lessons 1-4, so don't worry about skipping them. However, be sure to do all of the setup work that this lesson guides you through.

See bold items above.  Just some spelling issues and one error (I think).  I believe the bold "4" above should be "5".

**Comment by chrisbay** [comment]
Thanks, Laura. These have been fixed.
