### ISSUE TITLE
Assignment: TechJobs (Object-Oriented Edition) typo.

### ISSUE THREAD

**Issue by aguy01** [LaunchCodeEducation/skills-back-end-java#13]
Hi, 
I think new in JobController.new needs to be omitted. 

![image](https://cloud.githubusercontent.com/assets/23284338/24731354/79bba84c-1a37-11e7-98ac-cceda934e112.png)

> For tasks #3-5, you'll need to mimic the code that's in place for employerId and the employers list.
Once you have that stuff in place, you'll be ready to process the form in task #6. Validate the form in JobController.new, and if it's valid, create a new Job object and add it to the data layer by calling jobData.add(newJob).
[http://education.launchcode.org/skills-back-end-java/assignments/techjobs-oo/](url)

**Comment by chrisbay** [comment]
Fixed in 64f7baf149e16c6e2700640d385bd68c60131936
