### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by JenKocher** [LaunchCodeEducation/skills-back-end-java#14]
I think there are a couple of typos at this link:

http://education.launchcode.org/skills-back-end-java/java4python/data-structures-and-collections/

1) The language says:

"Once you've done that, let's look at what is happening in the Java source. The"

I think the last " The" is extraneous and can be deleted.

2) The language says:

"For each student that entered (that is,"

I think that should read: "For each student that is entered (that is,"

3) There is a period missing at the end of this sentence:
"There are lots of other list methods"

**Comment by chrisbay** [comment]
Fixed in 2818253d23e11c1dee5c053e15486cf19f4d0888
