### ISSUE TITLE
Typo - Data Structures and Collections

### ISSUE THREAD

**Issue by JenKocher** [LaunchCodeEducation/skills-back-end-java#15]
It looks like there's a typo on this page:
http://education.launchcode.org/skills-back-end-java/java4python/data-structures-and-collections/

The text currently reads:
"Notice that we declared grades to be of type ArrayList&lt;double&gt;, using the wrapper class Double rather than the primitive type double."

I believe the "double" in "ArrayList&lt;double&gt;" needs to start with an uppercase "D", like this:
"Notice that we declared grades to be of type ArrayList&lt;Double&gt;, using the wrapper class Double rather than the primitive type double."

**Comment by pdmxdd** [comment]
This issue was fixed, but never closed. Thanks!
