### ISSUE TITLE
Incorrect Field Mentioned

### ISSUE THREAD

**Issue by JenKocher** [LaunchCodeEducation/skills-back-end-java#16]
I don't know how much effort (if any) is going to be put into dealing with errata in the material for the course that just ended, but just in case it is going to be looked at while setting up the next iteration of material for the next course, I thought I'd point out the following.

I'm going back over material to reinforce my knowledge and I found the following error:

http://education.launchcode.org/skills-back-end-java/java4python/classes-and-objects-encapsulating-behavior/

Here's an excerpt from the code:

public Student(String name, int studentId,
            int numberOfCredits, double gpa) {
        this.name = name;
        this.studentId = studentId;
        this.numberOfCredits = numberOfCredits;
        this.gpa = gpa;
    }

    public Student(String name, int studentId) {
        this(name, studentId, 0, 0);
    }

The text says:
"In this case, the second constructor calls the first with the "default" values for studentId and gpa."

I believe this should read "...'default' values for numberOfCredits [not studentId] and gpa."

**Comment by pdmxdd** [comment]
This was also fixed, but never closed. Thanks!
