### ISSUE TITLE
Spring Boot intro asks students to use Spring Boot 1.5.12 

### ISSUE THREAD

**Issue by ryanawalker** [LaunchCodeEducation/skills-back-end-java#19]
https://education.launchcode.org/skills-back-end-java/videos/intro-to-spring-boot-controllers/

Instructions for setting up a Spring Boot app asks students to select Spring Boot 1.5.12 on start.spring.io, but that release is no longer an option on the site.

![image](https://user-images.githubusercontent.com/24947441/40140669-1b9cef60-5919-11e8-9b16-7b1d2ded3529.png)

**Comment by chrisbay** [comment]
@ryanawalker Thanks. To clarify, the important thing here is that they use the most recent non-SNAPSHOT 1.5.x release. The 2.x release series includes some updates to Spring Data that aren't supported yet by the curriculum.
