### ISSUE TITLE
errata: http://education.launchcode.org/skills-back-end-java/java4python/introduction/

### ISSUE THREAD

**Issue by ribex** [LaunchCodeEducation/skills-back-end-java#3]
large programs, languages like: For very **large, languages like programs** Java and C++

Throughout: **Throught** these initial lessons, we'll use a short comment at the top of each code sample to indicate which language is being used, to help you quickly tell while you're making the transition to Java.

look at a: Let's first **look a** version of Hello, World for Python:

is a: Here **is the a** Java program with the same functionality as the Python Hello, World program:

its: A method signature specifies all of the information necessary for a programmer to use the method, including, at minimum, **it's** name and the number, types, and order of its parameters.

its: When defining a class, we must surround the contents of the class (**it's** properties and methods) with "curly braces": { and }.

indentation: Instead of **indentattion**, what signifies to the compiler that this method definition is part of the Hello class is the fact that it is part of the block associated with that class.

**Comment by chrisbay** [comment]
Fixed in cfca2a348852d28704746062a9d5081ee1cd44d0
